#!/bin/bash
# skyops default user data script
# Rendered by Jinja2 — do not edit this file directly.
set -euo pipefail

USERNAME="{{ username }}"

# Create user if it doesn't exist
if ! id "$USERNAME" &>/dev/null; then
    useradd -m -s /bin/bash "$USERNAME"
fi

# Add user to sudo group
usermod -aG sudo "$USERNAME"

# Allow passwordless sudo
echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/"$USERNAME"
chmod 440 /etc/sudoers.d/"$USERNAME"

# Set up SSH authorized keys
SSH_DIR="/home/$USERNAME/.ssh"
mkdir -p "$SSH_DIR"
chmod 700 "$SSH_DIR"

cat > "$SSH_DIR/authorized_keys" << 'KEYS'
{% for key in ssh_keys %}{{ key }}
{% endfor %}KEYS

chmod 600 "$SSH_DIR/authorized_keys"
chown -R "$USERNAME:$USERNAME" "$SSH_DIR"

# Harden SSH: disable root login and password auth
sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config
sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
sed -i 's/^#\?ChallengeResponseAuthentication.*/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config

systemctl restart ssh || systemctl restart sshd || true

# Update package lists and install essentials
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq \
    curl \
    git \
    htop \
    jq \
    unzip \
    vim \
    wget

echo "skyops user data setup complete for user: $USERNAME"
